/********************************************************************************
** Form generated from reading UI file 'ReviewMode_NoGPS.ui'
**
** Created: Wed Jun 24 20:51:51 2015
**      by: Qt User Interface Compiler version 4.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GUIFRONTEND_H
#define UI_GUIFRONTEND_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDateEdit>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QListView>
#include <QtGui/QPushButton>
#include <QtGui/QTextEdit>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Form
{
public:
    QGroupBox *AnnotationFilter;
    QGroupBox *GrpFeature;
    QPushButton *btn_RL1;
    QPushButton *btn_LR1;
    QLabel *label_8;
    QListView *listFeatureSelected;
    QLabel *label_7;
    QListView *listFeature;
    QGroupBox *date;
    QDateEdit *dateEdit_2;
    QDateEdit *dateEdit;
    QLabel *label;
    QCheckBox *chk_date;
    QLabel *label_2;
    QGroupBox *groupBox;
    QCheckBox *chk_fcm_event;
    QCheckBox *chk_radar;
    QCheckBox *chk_user_event;
    QCheckBox *chk_eyeq_event;
    QGroupBox *groupBox_2;
    QCheckBox *chk_day_1;
    QCheckBox *chk_day_3;
    QCheckBox *chk_day_2;
    QGroupBox *groupBox_3;
    QCheckBox *chk_weather_1;
    QCheckBox *chk_weather_4;
    QCheckBox *chk_weather_3;
    QCheckBox *chk_weather_2;
    QGroupBox *groupBox_4;
    QCheckBox *chk_road_1;
    QCheckBox *chk_road_3;
    QCheckBox *chk_road_2;
    QGroupBox *groupBox_5;
    QCheckBox *chk_event_status_1;
    QCheckBox *chk_event_status_3;
    QCheckBox *chk_event_status_2;
    QCheckBox *chk_event_status_4;
    QCheckBox *chk_event_status_5;
    QGroupBox *GrpEvent;
    QListView *listAnnotation;
    QListView *listAnnotationSelected;
    QLabel *label_3;
    QListView *listEvent;
    QListView *listEventSelected;
    QPushButton *btn_RL3;
    QLabel *label_6;
    QPushButton *btn_LR3;
    QPushButton *btn_LR2;
    QLabel *label_4;
    QPushButton *btn_RL2;
    QCheckBox *chk_annotation;
    QCheckBox *chk_search;
    QLineEdit *txt_search;
    QLabel *listSelectedAI;
    QPushButton *btn_RL4;
    QListView *listAI;
    QListView *listAISelected;
    QPushButton *btn_LR4;
    QComboBox *cbo_AI;
    QCheckBox *chk_AI;
    QLabel *label_25;
    QLabel *label_27;
    QCheckBox *chk_tour;
    QComboBox *cbo_collection;
    QPushButton *btn_LR;
    QListView *listProject;
    QPushButton *btn_RL;
    QListView *listProjectSelected;
    QListView *listVin;
    QPushButton *btn_RL0;
    QListView *listVinSelected;
    QPushButton *btn_LR0;
    QLabel *label_28;
    QLabel *label_30;
    QGroupBox *GrpEdit;
    QGroupBox *grp_annotation;
    QPushButton *btn_insert;
    QPushButton *btn_copy;
    QCheckBox *chk_text_annotation;
    QLabel *lbl_clip;
    QPushButton *btn_next;
    QComboBox *cbo_status;
    QTextEdit *txt_annotation;
    QPushButton *btn_update;
    QLabel *lbl_table;
    QLabel *lbl_status;
    QLabel *lbl_reportid;
    QLabel *label_5;
    QPushButton *btn_prev;
    QComboBox *cbo_annotation;
    QListView *listEventAnnotation;
    QLabel *lbl_adtftime;
    QPushButton *btn_showclip;
    QGroupBox *grp_playlist;
    QListView *list_playlist;
    QPushButton *btn_generate;
    QLabel *lbl_status_playlist;
    QPushButton *btn_show_playlist;
    QGroupBox *GrpInsert;
    QPushButton *btn_submit;
    QPushButton *btn_cancel;
    QLineEdit *txt_clip;
    QLineEdit *txt_m;
    QLineEdit *txt_s;
    QComboBox *cbo_i_status;
    QComboBox *cbo_i_annotation;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_14;
    QLabel *label_15;
    QLineEdit *txt_ms;
    QLabel *label_16;
    QLabel *label_17;
    QComboBox *cbo_i_feature;
    QLabel *label_18;
    QComboBox *cbo_i_event;
    QLabel *label_19;
    QCheckBox *chk_i_text_annotation;
    QTextEdit *txt_i_annotation;
    QLabel *label_12;
    QComboBox *cbo_i_project;
    QComboBox *cbo_i_vin;
    QLabel *label_31;
    QPushButton *btn_setting;
    QLineEdit *txt_clip_directory;
    QPushButton *btn_clip;
    QGroupBox *grp_login;
    QLineEdit *txt_loginid;
    QLineEdit *txt_loginpw;
    QPushButton *btn_login;
    QLabel *label_23;
    QLabel *label_24;
    QPushButton *btn_change_pw;
    QGroupBox *grp_pwchange;
    QLineEdit *txt_change_id;
    QLineEdit *txt_cur_pw;
    QLineEdit *txt_change_pw;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QPushButton *btn_change;
    QPushButton *btn_change_cancel;
    QLineEdit *txt_change_pw2;
    QLabel *label_26;
    QLabel *lbl_user;
    QGroupBox *GrpSetting;
    QPushButton *btn_execute;
    QLineEdit *txt_sqlfile;
    QPushButton *btn_browse;
    QPushButton *btn_setting_cancel;
    QLabel *label_13;

    void setupUi(QWidget *Form)
    {
        if (Form->objectName().isEmpty())
            Form->setObjectName(QString::fromUtf8("Form"));
        Form->resize(1383, 901);
        AnnotationFilter = new QGroupBox(Form);
        AnnotationFilter->setObjectName(QString::fromUtf8("AnnotationFilter"));
        AnnotationFilter->setGeometry(QRect(10, 30, 1241, 461));
        GrpFeature = new QGroupBox(AnnotationFilter);
        GrpFeature->setObjectName(QString::fromUtf8("GrpFeature"));
        GrpFeature->setGeometry(QRect(10, 130, 1281, 171));
        btn_RL1 = new QPushButton(GrpFeature);
        btn_RL1->setObjectName(QString::fromUtf8("btn_RL1"));
        btn_RL1->setGeometry(QRect(200, 100, 31, 23));
        btn_LR1 = new QPushButton(GrpFeature);
        btn_LR1->setObjectName(QString::fromUtf8("btn_LR1"));
        btn_LR1->setGeometry(QRect(200, 70, 31, 23));
        label_8 = new QLabel(GrpFeature);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(250, 20, 151, 16));
        label_8->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        listFeatureSelected = new QListView(GrpFeature);
        listFeatureSelected->setObjectName(QString::fromUtf8("listFeatureSelected"));
        listFeatureSelected->setGeometry(QRect(240, 40, 171, 111));
        listFeatureSelected->setSelectionMode(QAbstractItemView::MultiSelection);
        label_7 = new QLabel(GrpFeature);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(60, 20, 101, 16));
        listFeature = new QListView(GrpFeature);
        listFeature->setObjectName(QString::fromUtf8("listFeature"));
        listFeature->setGeometry(QRect(20, 40, 171, 111));
        listFeature->setSelectionMode(QAbstractItemView::MultiSelection);
        date = new QGroupBox(GrpFeature);
        date->setObjectName(QString::fromUtf8("date"));
        date->setGeometry(QRect(440, 20, 161, 131));
        dateEdit_2 = new QDateEdit(date);
        dateEdit_2->setObjectName(QString::fromUtf8("dateEdit_2"));
        dateEdit_2->setEnabled(false);
        dateEdit_2->setGeometry(QRect(60, 90, 91, 31));
        dateEdit_2->setCurrentSection(QDateTimeEdit::YearSection);
        dateEdit_2->setCalendarPopup(true);
        dateEdit = new QDateEdit(date);
        dateEdit->setObjectName(QString::fromUtf8("dateEdit"));
        dateEdit->setEnabled(false);
        dateEdit->setGeometry(QRect(60, 41, 91, 31));
        dateEdit->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        dateEdit->setCurrentSection(QDateTimeEdit::YearSection);
        dateEdit->setCalendarPopup(true);
        label = new QLabel(date);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 50, 46, 13));
        label->setAlignment(Qt::AlignCenter);
        chk_date = new QCheckBox(date);
        chk_date->setObjectName(QString::fromUtf8("chk_date"));
        chk_date->setGeometry(QRect(20, 20, 101, 17));
        chk_date->setCheckable(true);
        chk_date->setChecked(true);
        label_2 = new QLabel(date);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 100, 46, 13));
        label_2->setAlignment(Qt::AlignCenter);
        groupBox = new QGroupBox(GrpFeature);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(626, 20, 101, 131));
        chk_fcm_event = new QCheckBox(groupBox);
        chk_fcm_event->setObjectName(QString::fromUtf8("chk_fcm_event"));
        chk_fcm_event->setGeometry(QRect(15, 26, 81, 17));
        chk_fcm_event->setChecked(true);
        chk_radar = new QCheckBox(groupBox);
        chk_radar->setObjectName(QString::fromUtf8("chk_radar"));
        chk_radar->setGeometry(QRect(15, 103, 91, 17));
        chk_radar->setChecked(true);
        chk_user_event = new QCheckBox(groupBox);
        chk_user_event->setObjectName(QString::fromUtf8("chk_user_event"));
        chk_user_event->setGeometry(QRect(15, 77, 91, 17));
        chk_user_event->setChecked(true);
        chk_eyeq_event = new QCheckBox(groupBox);
        chk_eyeq_event->setObjectName(QString::fromUtf8("chk_eyeq_event"));
        chk_eyeq_event->setGeometry(QRect(15, 51, 81, 17));
        chk_eyeq_event->setChecked(true);
        groupBox_2 = new QGroupBox(GrpFeature);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(750, 20, 81, 131));
        chk_day_1 = new QCheckBox(groupBox_2);
        chk_day_1->setObjectName(QString::fromUtf8("chk_day_1"));
        chk_day_1->setGeometry(QRect(15, 26, 41, 17));
        chk_day_1->setChecked(true);
        chk_day_3 = new QCheckBox(groupBox_2);
        chk_day_3->setObjectName(QString::fromUtf8("chk_day_3"));
        chk_day_3->setGeometry(QRect(15, 100, 51, 17));
        chk_day_3->setChecked(true);
        chk_day_2 = new QCheckBox(groupBox_2);
        chk_day_2->setObjectName(QString::fromUtf8("chk_day_2"));
        chk_day_2->setGeometry(QRect(15, 63, 51, 17));
        chk_day_2->setChecked(true);
        groupBox_3 = new QGroupBox(GrpFeature);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(860, 20, 91, 131));
        chk_weather_1 = new QCheckBox(groupBox_3);
        chk_weather_1->setObjectName(QString::fromUtf8("chk_weather_1"));
        chk_weather_1->setGeometry(QRect(15, 26, 51, 17));
        chk_weather_1->setChecked(true);
        chk_weather_4 = new QCheckBox(groupBox_3);
        chk_weather_4->setObjectName(QString::fromUtf8("chk_weather_4"));
        chk_weather_4->setGeometry(QRect(15, 103, 51, 17));
        chk_weather_4->setChecked(true);
        chk_weather_3 = new QCheckBox(groupBox_3);
        chk_weather_3->setObjectName(QString::fromUtf8("chk_weather_3"));
        chk_weather_3->setGeometry(QRect(15, 77, 71, 17));
        chk_weather_3->setChecked(true);
        chk_weather_2 = new QCheckBox(groupBox_3);
        chk_weather_2->setObjectName(QString::fromUtf8("chk_weather_2"));
        chk_weather_2->setGeometry(QRect(15, 51, 51, 17));
        chk_weather_2->setChecked(true);
        groupBox_4 = new QGroupBox(GrpFeature);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(980, 20, 91, 131));
        chk_road_1 = new QCheckBox(groupBox_4);
        chk_road_1->setObjectName(QString::fromUtf8("chk_road_1"));
        chk_road_1->setGeometry(QRect(15, 26, 61, 17));
        chk_road_1->setChecked(true);
        chk_road_3 = new QCheckBox(groupBox_4);
        chk_road_3->setObjectName(QString::fromUtf8("chk_road_3"));
        chk_road_3->setGeometry(QRect(15, 103, 41, 17));
        chk_road_3->setChecked(true);
        chk_road_2 = new QCheckBox(groupBox_4);
        chk_road_2->setObjectName(QString::fromUtf8("chk_road_2"));
        chk_road_2->setGeometry(QRect(15, 65, 51, 17));
        chk_road_2->setChecked(true);
        groupBox_5 = new QGroupBox(GrpFeature);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(1100, 20, 121, 131));
        chk_event_status_1 = new QCheckBox(groupBox_5);
        chk_event_status_1->setObjectName(QString::fromUtf8("chk_event_status_1"));
        chk_event_status_1->setGeometry(QRect(15, 26, 91, 17));
        chk_event_status_1->setChecked(true);
        chk_event_status_3 = new QCheckBox(groupBox_5);
        chk_event_status_3->setObjectName(QString::fromUtf8("chk_event_status_3"));
        chk_event_status_3->setGeometry(QRect(15, 63, 81, 17));
        chk_event_status_3->setChecked(true);
        chk_event_status_2 = new QCheckBox(groupBox_5);
        chk_event_status_2->setObjectName(QString::fromUtf8("chk_event_status_2"));
        chk_event_status_2->setGeometry(QRect(15, 44, 51, 17));
        chk_event_status_2->setChecked(true);
        chk_event_status_4 = new QCheckBox(groupBox_5);
        chk_event_status_4->setObjectName(QString::fromUtf8("chk_event_status_4"));
        chk_event_status_4->setGeometry(QRect(15, 83, 61, 17));
        chk_event_status_4->setChecked(true);
        chk_event_status_5 = new QCheckBox(groupBox_5);
        chk_event_status_5->setObjectName(QString::fromUtf8("chk_event_status_5"));
        chk_event_status_5->setGeometry(QRect(15, 103, 61, 17));
        chk_event_status_5->setChecked(true);
        GrpEvent = new QGroupBox(AnnotationFilter);
        GrpEvent->setObjectName(QString::fromUtf8("GrpEvent"));
        GrpEvent->setEnabled(true);
        GrpEvent->setGeometry(QRect(10, 300, 1221, 151));
        listAnnotation = new QListView(GrpEvent);
        listAnnotation->setObjectName(QString::fromUtf8("listAnnotation"));
        listAnnotation->setGeometry(QRect(391, 40, 170, 101));
        listAnnotation->setSelectionMode(QAbstractItemView::MultiSelection);
        listAnnotationSelected = new QListView(GrpEvent);
        listAnnotationSelected->setObjectName(QString::fromUtf8("listAnnotationSelected"));
        listAnnotationSelected->setGeometry(QRect(611, 40, 170, 101));
        listAnnotationSelected->setSelectionMode(QAbstractItemView::MultiSelection);
        label_3 = new QLabel(GrpEvent);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(80, 16, 41, 16));
        label_3->setLayoutDirection(Qt::LeftToRight);
        listEvent = new QListView(GrpEvent);
        listEvent->setObjectName(QString::fromUtf8("listEvent"));
        listEvent->setGeometry(QRect(20, 40, 151, 101));
        listEvent->setSelectionMode(QAbstractItemView::MultiSelection);
        listEventSelected = new QListView(GrpEvent);
        listEventSelected->setObjectName(QString::fromUtf8("listEventSelected"));
        listEventSelected->setGeometry(QRect(220, 40, 151, 101));
        listEventSelected->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_RL3 = new QPushButton(GrpEvent);
        btn_RL3->setObjectName(QString::fromUtf8("btn_RL3"));
        btn_RL3->setGeometry(QRect(571, 96, 31, 23));
        label_6 = new QLabel(GrpEvent);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(621, 16, 161, 20));
        btn_LR3 = new QPushButton(GrpEvent);
        btn_LR3->setObjectName(QString::fromUtf8("btn_LR3"));
        btn_LR3->setGeometry(QRect(571, 66, 31, 23));
        btn_LR2 = new QPushButton(GrpEvent);
        btn_LR2->setObjectName(QString::fromUtf8("btn_LR2"));
        btn_LR2->setGeometry(QRect(180, 66, 31, 23));
        label_4 = new QLabel(GrpEvent);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(260, 16, 81, 16));
        btn_RL2 = new QPushButton(GrpEvent);
        btn_RL2->setObjectName(QString::fromUtf8("btn_RL2"));
        btn_RL2->setGeometry(QRect(180, 96, 31, 23));
        chk_annotation = new QCheckBox(GrpEvent);
        chk_annotation->setObjectName(QString::fromUtf8("chk_annotation"));
        chk_annotation->setGeometry(QRect(451, 17, 151, 17));
        chk_search = new QCheckBox(GrpEvent);
        chk_search->setObjectName(QString::fromUtf8("chk_search"));
        chk_search->setGeometry(QRect(376, 16, 71, 17));
        chk_search->setChecked(true);
        txt_search = new QLineEdit(GrpEvent);
        txt_search->setObjectName(QString::fromUtf8("txt_search"));
        txt_search->setGeometry(QRect(450, 15, 331, 20));
        listSelectedAI = new QLabel(GrpEvent);
        listSelectedAI->setObjectName(QString::fromUtf8("listSelectedAI"));
        listSelectedAI->setGeometry(QRect(1070, 14, 101, 20));
        btn_RL4 = new QPushButton(GrpEvent);
        btn_RL4->setObjectName(QString::fromUtf8("btn_RL4"));
        btn_RL4->setGeometry(QRect(985, 96, 41, 23));
        QFont font;
        font.setPointSize(6);
        btn_RL4->setFont(font);
        listAI = new QListView(GrpEvent);
        listAI->setObjectName(QString::fromUtf8("listAI"));
        listAI->setGeometry(QRect(800, 40, 181, 101));
        listAI->setSelectionMode(QAbstractItemView::MultiSelection);
        listAISelected = new QListView(GrpEvent);
        listAISelected->setObjectName(QString::fromUtf8("listAISelected"));
        listAISelected->setGeometry(QRect(1030, 40, 181, 101));
        listAISelected->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_LR4 = new QPushButton(GrpEvent);
        btn_LR4->setObjectName(QString::fromUtf8("btn_LR4"));
        btn_LR4->setGeometry(QRect(985, 66, 41, 23));
        btn_LR4->setFont(font);
        cbo_AI = new QComboBox(GrpEvent);
        cbo_AI->setObjectName(QString::fromUtf8("cbo_AI"));
        cbo_AI->setGeometry(QRect(850, 12, 131, 22));
        chk_AI = new QCheckBox(GrpEvent);
        chk_AI->setObjectName(QString::fromUtf8("chk_AI"));
        chk_AI->setGeometry(QRect(800, 15, 70, 17));
        chk_AI->setChecked(true);
        label_25 = new QLabel(AnnotationFilter);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(90, 20, 46, 13));
        label_27 = new QLabel(AnnotationFilter);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(293, 20, 81, 16));
        chk_tour = new QCheckBox(AnnotationFilter);
        chk_tour->setObjectName(QString::fromUtf8("chk_tour"));
        chk_tour->setGeometry(QRect(860, 20, 91, 17));
        chk_tour->setChecked(true);
        cbo_collection = new QComboBox(AnnotationFilter);
        cbo_collection->setObjectName(QString::fromUtf8("cbo_collection"));
        cbo_collection->setGeometry(QRect(860, 40, 301, 22));
        btn_LR = new QPushButton(AnnotationFilter);
        btn_LR->setObjectName(QString::fromUtf8("btn_LR"));
        btn_LR->setGeometry(QRect(210, 50, 31, 23));
        listProject = new QListView(AnnotationFilter);
        listProject->setObjectName(QString::fromUtf8("listProject"));
        listProject->setGeometry(QRect(30, 40, 171, 81));
        listProject->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_RL = new QPushButton(AnnotationFilter);
        btn_RL->setObjectName(QString::fromUtf8("btn_RL"));
        btn_RL->setGeometry(QRect(210, 80, 31, 23));
        listProjectSelected = new QListView(AnnotationFilter);
        listProjectSelected->setObjectName(QString::fromUtf8("listProjectSelected"));
        listProjectSelected->setGeometry(QRect(250, 40, 171, 81));
        listProjectSelected->setSelectionMode(QAbstractItemView::MultiSelection);
        listVin = new QListView(AnnotationFilter);
        listVin->setObjectName(QString::fromUtf8("listVin"));
        listVin->setGeometry(QRect(450, 40, 171, 81));
        listVin->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_RL0 = new QPushButton(AnnotationFilter);
        btn_RL0->setObjectName(QString::fromUtf8("btn_RL0"));
        btn_RL0->setGeometry(QRect(630, 80, 31, 23));
        listVinSelected = new QListView(AnnotationFilter);
        listVinSelected->setObjectName(QString::fromUtf8("listVinSelected"));
        listVinSelected->setGeometry(QRect(670, 40, 171, 81));
        listVinSelected->setSelectionMode(QAbstractItemView::MultiSelection);
        btn_LR0 = new QPushButton(AnnotationFilter);
        btn_LR0->setObjectName(QString::fromUtf8("btn_LR0"));
        btn_LR0->setGeometry(QRect(630, 50, 31, 23));
        label_28 = new QLabel(AnnotationFilter);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(721, 20, 71, 16));
        label_30 = new QLabel(AnnotationFilter);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(526, 20, 46, 13));
        GrpEdit = new QGroupBox(Form);
        GrpEdit->setObjectName(QString::fromUtf8("GrpEdit"));
        GrpEdit->setGeometry(QRect(10, 500, 1241, 251));
        grp_annotation = new QGroupBox(GrpEdit);
        grp_annotation->setObjectName(QString::fromUtf8("grp_annotation"));
        grp_annotation->setGeometry(QRect(370, 20, 861, 211));
        btn_insert = new QPushButton(grp_annotation);
        btn_insert->setObjectName(QString::fromUtf8("btn_insert"));
        btn_insert->setGeometry(QRect(690, 150, 151, 31));
        btn_copy = new QPushButton(grp_annotation);
        btn_copy->setObjectName(QString::fromUtf8("btn_copy"));
        btn_copy->setGeometry(QRect(690, 60, 151, 31));
        chk_text_annotation = new QCheckBox(grp_annotation);
        chk_text_annotation->setObjectName(QString::fromUtf8("chk_text_annotation"));
        chk_text_annotation->setGeometry(QRect(460, 60, 151, 17));
        chk_text_annotation->setChecked(true);
        lbl_clip = new QLabel(grp_annotation);
        lbl_clip->setObjectName(QString::fromUtf8("lbl_clip"));
        lbl_clip->setGeometry(QRect(460, 40, 381, 16));
        btn_next = new QPushButton(grp_annotation);
        btn_next->setObjectName(QString::fromUtf8("btn_next"));
        btn_next->setGeometry(QRect(260, 152, 181, 31));
        cbo_status = new QComboBox(grp_annotation);
        cbo_status->setObjectName(QString::fromUtf8("cbo_status"));
        cbo_status->setGeometry(QRect(460, 152, 221, 31));
        txt_annotation = new QTextEdit(grp_annotation);
        txt_annotation->setObjectName(QString::fromUtf8("txt_annotation"));
        txt_annotation->setGeometry(QRect(460, 80, 221, 51));
        btn_update = new QPushButton(grp_annotation);
        btn_update->setObjectName(QString::fromUtf8("btn_update"));
        btn_update->setGeometry(QRect(690, 120, 151, 31));
        lbl_table = new QLabel(grp_annotation);
        lbl_table->setObjectName(QString::fromUtf8("lbl_table"));
        lbl_table->setGeometry(QRect(410, 10, 46, 13));
        lbl_status = new QLabel(grp_annotation);
        lbl_status->setObjectName(QString::fromUtf8("lbl_status"));
        lbl_status->setGeometry(QRect(10, 190, 851, 16));
        lbl_reportid = new QLabel(grp_annotation);
        lbl_reportid->setObjectName(QString::fromUtf8("lbl_reportid"));
        lbl_reportid->setGeometry(QRect(320, 10, 46, 13));
        label_5 = new QLabel(grp_annotation);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(470, 132, 71, 16));
        btn_prev = new QPushButton(grp_annotation);
        btn_prev->setObjectName(QString::fromUtf8("btn_prev"));
        btn_prev->setGeometry(QRect(30, 152, 181, 31));
        cbo_annotation = new QComboBox(grp_annotation);
        cbo_annotation->setObjectName(QString::fromUtf8("cbo_annotation"));
        cbo_annotation->setGeometry(QRect(460, 80, 221, 31));
        listEventAnnotation = new QListView(grp_annotation);
        listEventAnnotation->setObjectName(QString::fromUtf8("listEventAnnotation"));
        listEventAnnotation->setEnabled(true);
        listEventAnnotation->setGeometry(QRect(30, 30, 411, 121));
        lbl_adtftime = new QLabel(grp_annotation);
        lbl_adtftime->setObjectName(QString::fromUtf8("lbl_adtftime"));
        lbl_adtftime->setGeometry(QRect(460, 20, 171, 20));
        btn_showclip = new QPushButton(grp_annotation);
        btn_showclip->setObjectName(QString::fromUtf8("btn_showclip"));
        btn_showclip->setGeometry(QRect(690, 90, 151, 31));
        grp_playlist = new QGroupBox(GrpEdit);
        grp_playlist->setObjectName(QString::fromUtf8("grp_playlist"));
        grp_playlist->setGeometry(QRect(10, 19, 331, 211));
        list_playlist = new QListView(grp_playlist);
        list_playlist->setObjectName(QString::fromUtf8("list_playlist"));
        list_playlist->setEnabled(true);
        list_playlist->setGeometry(QRect(10, 30, 311, 121));
        btn_generate = new QPushButton(grp_playlist);
        btn_generate->setObjectName(QString::fromUtf8("btn_generate"));
        btn_generate->setGeometry(QRect(10, 153, 311, 31));
        lbl_status_playlist = new QLabel(grp_playlist);
        lbl_status_playlist->setObjectName(QString::fromUtf8("lbl_status_playlist"));
        lbl_status_playlist->setGeometry(QRect(10, 190, 311, 16));
        btn_show_playlist = new QPushButton(GrpEdit);
        btn_show_playlist->setObjectName(QString::fromUtf8("btn_show_playlist"));
        btn_show_playlist->setGeometry(QRect(345, 22, 20, 211));
        GrpInsert = new QGroupBox(Form);
        GrpInsert->setObjectName(QString::fromUtf8("GrpInsert"));
        GrpInsert->setGeometry(QRect(530, 770, 561, 261));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 170, 127, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(255, 212, 191, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(127, 85, 63, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(170, 113, 84, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush6(QColor(255, 255, 220, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        GrpInsert->setPalette(palette);
        GrpInsert->setAutoFillBackground(true);
        btn_submit = new QPushButton(GrpInsert);
        btn_submit->setObjectName(QString::fromUtf8("btn_submit"));
        btn_submit->setGeometry(QRect(420, 180, 111, 71));
        btn_submit->setFocusPolicy(Qt::StrongFocus);
        btn_cancel = new QPushButton(GrpInsert);
        btn_cancel->setObjectName(QString::fromUtf8("btn_cancel"));
        btn_cancel->setGeometry(QRect(420, 100, 111, 71));
        btn_cancel->setFocusPolicy(Qt::StrongFocus);
        txt_clip = new QLineEdit(GrpInsert);
        txt_clip->setObjectName(QString::fromUtf8("txt_clip"));
        txt_clip->setGeometry(QRect(20, 50, 211, 20));
        txt_clip->setFocusPolicy(Qt::StrongFocus);
        txt_m = new QLineEdit(GrpInsert);
        txt_m->setObjectName(QString::fromUtf8("txt_m"));
        txt_m->setGeometry(QRect(250, 50, 31, 20));
        txt_m->setFocusPolicy(Qt::StrongFocus);
        txt_s = new QLineEdit(GrpInsert);
        txt_s->setObjectName(QString::fromUtf8("txt_s"));
        txt_s->setGeometry(QRect(300, 50, 31, 20));
        txt_s->setFocusPolicy(Qt::StrongFocus);
        cbo_i_status = new QComboBox(GrpInsert);
        cbo_i_status->setObjectName(QString::fromUtf8("cbo_i_status"));
        cbo_i_status->setGeometry(QRect(20, 200, 181, 22));
        cbo_i_status->setFocusPolicy(Qt::StrongFocus);
        cbo_i_status->setMaxVisibleItems(10);
        cbo_i_status->setSizeAdjustPolicy(QComboBox::AdjustToContentsOnFirstShow);
        cbo_i_annotation = new QComboBox(GrpInsert);
        cbo_i_annotation->setObjectName(QString::fromUtf8("cbo_i_annotation"));
        cbo_i_annotation->setGeometry(QRect(220, 200, 191, 22));
        cbo_i_annotation->setFocusPolicy(Qt::StrongFocus);
        cbo_i_annotation->setMaxVisibleItems(10);
        cbo_i_annotation->setSizeAdjustPolicy(QComboBox::AdjustToContentsOnFirstShow);
        label_9 = new QLabel(GrpInsert);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(20, 30, 201, 16));
        label_9->setAlignment(Qt::AlignCenter);
        label_10 = new QLabel(GrpInsert);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(230, 30, 191, 16));
        label_10->setAlignment(Qt::AlignCenter);
        label_11 = new QLabel(GrpInsert);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(50, 180, 141, 16));
        label_11->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(GrpInsert);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(290, 50, 16, 16));
        label_15 = new QLabel(GrpInsert);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(340, 50, 16, 16));
        txt_ms = new QLineEdit(GrpInsert);
        txt_ms->setObjectName(QString::fromUtf8("txt_ms"));
        txt_ms->setGeometry(QRect(350, 50, 31, 20));
        txt_ms->setFocusPolicy(Qt::StrongFocus);
        label_16 = new QLabel(GrpInsert);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(390, 50, 16, 16));
        label_17 = new QLabel(GrpInsert);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(50, 130, 141, 16));
        label_17->setAlignment(Qt::AlignCenter);
        cbo_i_feature = new QComboBox(GrpInsert);
        cbo_i_feature->setObjectName(QString::fromUtf8("cbo_i_feature"));
        cbo_i_feature->setGeometry(QRect(20, 150, 181, 22));
        cbo_i_feature->setFocusPolicy(Qt::StrongFocus);
        cbo_i_feature->setMaxVisibleItems(10);
        cbo_i_feature->setSizeAdjustPolicy(QComboBox::AdjustToContentsOnFirstShow);
        label_18 = new QLabel(GrpInsert);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(240, 130, 141, 16));
        label_18->setAlignment(Qt::AlignCenter);
        cbo_i_event = new QComboBox(GrpInsert);
        cbo_i_event->setObjectName(QString::fromUtf8("cbo_i_event"));
        cbo_i_event->setGeometry(QRect(220, 150, 191, 20));
        cbo_i_event->setFocusPolicy(Qt::WheelFocus);
        cbo_i_event->setAcceptDrops(false);
        cbo_i_event->setMaxVisibleItems(10);
        cbo_i_event->setSizeAdjustPolicy(QComboBox::AdjustToContentsOnFirstShow);
        label_19 = new QLabel(GrpInsert);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(250, 80, 141, 16));
        label_19->setAlignment(Qt::AlignCenter);
        chk_i_text_annotation = new QCheckBox(GrpInsert);
        chk_i_text_annotation->setObjectName(QString::fromUtf8("chk_i_text_annotation"));
        chk_i_text_annotation->setGeometry(QRect(270, 170, 91, 20));
        chk_i_text_annotation->setChecked(true);
        txt_i_annotation = new QTextEdit(GrpInsert);
        txt_i_annotation->setObjectName(QString::fromUtf8("txt_i_annotation"));
        txt_i_annotation->setGeometry(QRect(220, 200, 191, 41));
        label_12 = new QLabel(GrpInsert);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(410, 30, 141, 41));
        QFont font1;
        font1.setPointSize(12);
        font1.setBold(true);
        font1.setWeight(75);
        label_12->setFont(font1);
        label_12->setAlignment(Qt::AlignCenter);
        cbo_i_project = new QComboBox(GrpInsert);
        cbo_i_project->setObjectName(QString::fromUtf8("cbo_i_project"));
        cbo_i_project->setGeometry(QRect(20, 100, 181, 22));
        cbo_i_vin = new QComboBox(GrpInsert);
        cbo_i_vin->setObjectName(QString::fromUtf8("cbo_i_vin"));
        cbo_i_vin->setGeometry(QRect(220, 100, 191, 22));
        label_31 = new QLabel(GrpInsert);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(43, 80, 141, 16));
        label_31->setAlignment(Qt::AlignCenter);
        btn_setting = new QPushButton(Form);
        btn_setting->setObjectName(QString::fromUtf8("btn_setting"));
        btn_setting->setGeometry(QRect(1100, 10, 91, 21));
        txt_clip_directory = new QLineEdit(Form);
        txt_clip_directory->setObjectName(QString::fromUtf8("txt_clip_directory"));
        txt_clip_directory->setGeometry(QRect(12, 10, 371, 21));
        btn_clip = new QPushButton(Form);
        btn_clip->setObjectName(QString::fromUtf8("btn_clip"));
        btn_clip->setGeometry(QRect(390, 10, 121, 21));
        grp_login = new QGroupBox(Form);
        grp_login->setObjectName(QString::fromUtf8("grp_login"));
        grp_login->setGeometry(QRect(530, 290, 231, 121));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush7(QColor(170, 255, 255, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush8(QColor(212, 255, 255, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush8);
        QBrush brush9(QColor(85, 127, 127, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush9);
        QBrush brush10(QColor(113, 170, 170, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush7);
        QBrush brush11(QColor(85, 255, 255, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush11);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush11);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        grp_login->setPalette(palette1);
        grp_login->setAutoFillBackground(true);
        txt_loginid = new QLineEdit(grp_login);
        txt_loginid->setObjectName(QString::fromUtf8("txt_loginid"));
        txt_loginid->setGeometry(QRect(90, 20, 113, 20));
        txt_loginpw = new QLineEdit(grp_login);
        txt_loginpw->setObjectName(QString::fromUtf8("txt_loginpw"));
        txt_loginpw->setGeometry(QRect(90, 50, 113, 20));
        btn_login = new QPushButton(grp_login);
        btn_login->setObjectName(QString::fromUtf8("btn_login"));
        btn_login->setGeometry(QRect(90, 80, 111, 23));
        label_23 = new QLabel(grp_login);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(20, 25, 46, 13));
        label_24 = new QLabel(grp_login);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(20, 53, 46, 13));
        btn_change_pw = new QPushButton(grp_login);
        btn_change_pw->setObjectName(QString::fromUtf8("btn_change_pw"));
        btn_change_pw->setGeometry(QRect(10, 80, 75, 23));
        grp_pwchange = new QGroupBox(Form);
        grp_pwchange->setObjectName(QString::fromUtf8("grp_pwchange"));
        grp_pwchange->setGeometry(QRect(530, 410, 231, 181));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush8);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        grp_pwchange->setPalette(palette2);
        grp_pwchange->setAutoFillBackground(true);
        txt_change_id = new QLineEdit(grp_pwchange);
        txt_change_id->setObjectName(QString::fromUtf8("txt_change_id"));
        txt_change_id->setGeometry(QRect(90, 20, 113, 20));
        txt_cur_pw = new QLineEdit(grp_pwchange);
        txt_cur_pw->setObjectName(QString::fromUtf8("txt_cur_pw"));
        txt_cur_pw->setGeometry(QRect(90, 50, 113, 20));
        txt_change_pw = new QLineEdit(grp_pwchange);
        txt_change_pw->setObjectName(QString::fromUtf8("txt_change_pw"));
        txt_change_pw->setGeometry(QRect(90, 80, 113, 20));
        label_20 = new QLabel(grp_pwchange);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(20, 25, 46, 13));
        label_21 = new QLabel(grp_pwchange);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(20, 54, 61, 16));
        label_22 = new QLabel(grp_pwchange);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(20, 85, 46, 13));
        label_22->setFrameShape(QFrame::NoFrame);
        label_22->setFrameShadow(QFrame::Plain);
        btn_change = new QPushButton(grp_pwchange);
        btn_change->setObjectName(QString::fromUtf8("btn_change"));
        btn_change->setGeometry(QRect(110, 150, 91, 23));
        btn_change_cancel = new QPushButton(grp_pwchange);
        btn_change_cancel->setObjectName(QString::fromUtf8("btn_change_cancel"));
        btn_change_cancel->setGeometry(QRect(16, 150, 91, 23));
        txt_change_pw2 = new QLineEdit(grp_pwchange);
        txt_change_pw2->setObjectName(QString::fromUtf8("txt_change_pw2"));
        txt_change_pw2->setGeometry(QRect(90, 110, 113, 20));
        label_26 = new QLabel(grp_pwchange);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(21, 114, 61, 16));
        lbl_user = new QLabel(Form);
        lbl_user->setObjectName(QString::fromUtf8("lbl_user"));
        lbl_user->setGeometry(QRect(520, 13, 181, 16));
        GrpSetting = new QGroupBox(Form);
        GrpSetting->setObjectName(QString::fromUtf8("GrpSetting"));
        GrpSetting->setGeometry(QRect(770, 10, 321, 161));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        GrpSetting->setPalette(palette3);
        GrpSetting->setAutoFillBackground(true);
        btn_execute = new QPushButton(GrpSetting);
        btn_execute->setObjectName(QString::fromUtf8("btn_execute"));
        btn_execute->setEnabled(true);
        btn_execute->setGeometry(QRect(130, 90, 171, 51));
        txt_sqlfile = new QLineEdit(GrpSetting);
        txt_sqlfile->setObjectName(QString::fromUtf8("txt_sqlfile"));
        txt_sqlfile->setEnabled(true);
        txt_sqlfile->setGeometry(QRect(20, 60, 171, 21));
        btn_browse = new QPushButton(GrpSetting);
        btn_browse->setObjectName(QString::fromUtf8("btn_browse"));
        btn_browse->setGeometry(QRect(200, 60, 101, 21));
        btn_setting_cancel = new QPushButton(GrpSetting);
        btn_setting_cancel->setObjectName(QString::fromUtf8("btn_setting_cancel"));
        btn_setting_cancel->setGeometry(QRect(20, 90, 101, 51));
        label_13 = new QLabel(GrpSetting);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(30, 20, 181, 31));
        label_13->setFont(font1);
        label_13->setAlignment(Qt::AlignCenter);
        QWidget::setTabOrder(listAnnotationSelected, btn_update);
        QWidget::setTabOrder(btn_update, cbo_annotation);
        QWidget::setTabOrder(cbo_annotation, cbo_status);
        QWidget::setTabOrder(cbo_status, btn_insert);
        QWidget::setTabOrder(btn_insert, btn_showclip);
        QWidget::setTabOrder(btn_showclip, txt_clip);
        QWidget::setTabOrder(txt_clip, txt_m);
        QWidget::setTabOrder(txt_m, txt_s);
        QWidget::setTabOrder(txt_s, txt_ms);
        QWidget::setTabOrder(txt_ms, cbo_i_feature);
        QWidget::setTabOrder(cbo_i_feature, cbo_i_event);
        QWidget::setTabOrder(cbo_i_event, cbo_i_status);
        QWidget::setTabOrder(cbo_i_status, chk_i_text_annotation);
        QWidget::setTabOrder(chk_i_text_annotation, cbo_i_annotation);
        QWidget::setTabOrder(cbo_i_annotation, txt_i_annotation);
        QWidget::setTabOrder(txt_i_annotation, btn_submit);
        QWidget::setTabOrder(btn_submit, btn_cancel);
        QWidget::setTabOrder(btn_cancel, listEventAnnotation);
        QWidget::setTabOrder(listEventAnnotation, btn_RL1);
        QWidget::setTabOrder(btn_RL1, btn_LR1);
        QWidget::setTabOrder(btn_LR1, listFeatureSelected);
        QWidget::setTabOrder(listFeatureSelected, listFeature);
        QWidget::setTabOrder(listFeature, dateEdit);
        QWidget::setTabOrder(dateEdit, dateEdit_2);
        QWidget::setTabOrder(dateEdit_2, chk_user_event);
        QWidget::setTabOrder(chk_user_event, chk_eyeq_event);
        QWidget::setTabOrder(chk_eyeq_event, chk_fcm_event);
        QWidget::setTabOrder(chk_fcm_event, chk_date);
        QWidget::setTabOrder(chk_date, listAnnotation);
        QWidget::setTabOrder(listAnnotation, listEvent);
        QWidget::setTabOrder(listEvent, listEventSelected);
        QWidget::setTabOrder(listEventSelected, btn_RL3);
        QWidget::setTabOrder(btn_RL3, btn_LR3);
        QWidget::setTabOrder(btn_LR3, btn_LR2);
        QWidget::setTabOrder(btn_LR2, btn_RL2);
        QWidget::setTabOrder(btn_RL2, chk_annotation);
        QWidget::setTabOrder(chk_annotation, chk_text_annotation);
        QWidget::setTabOrder(chk_text_annotation, txt_annotation);
        QWidget::setTabOrder(txt_annotation, btn_setting);
        QWidget::setTabOrder(btn_setting, txt_clip_directory);
        QWidget::setTabOrder(txt_clip_directory, btn_clip);
        QWidget::setTabOrder(btn_clip, btn_copy);
        QWidget::setTabOrder(btn_copy, btn_execute);
        QWidget::setTabOrder(btn_execute, txt_sqlfile);
        QWidget::setTabOrder(txt_sqlfile, btn_browse);
        QWidget::setTabOrder(btn_browse, btn_setting_cancel);
        QWidget::setTabOrder(btn_setting_cancel, txt_loginid);
        QWidget::setTabOrder(txt_loginid, txt_loginpw);
        QWidget::setTabOrder(txt_loginpw, btn_login);
        QWidget::setTabOrder(btn_login, btn_change_pw);
        QWidget::setTabOrder(btn_change_pw, txt_change_id);
        QWidget::setTabOrder(txt_change_id, txt_cur_pw);
        QWidget::setTabOrder(txt_cur_pw, txt_change_pw);
        QWidget::setTabOrder(txt_change_pw, txt_change_pw2);
        QWidget::setTabOrder(txt_change_pw2, btn_change);
        QWidget::setTabOrder(btn_change, btn_change_cancel);
        QWidget::setTabOrder(btn_change_cancel, chk_radar);
        QWidget::setTabOrder(chk_radar, chk_search);
        QWidget::setTabOrder(chk_search, txt_search);

        retranslateUi(Form);

        QMetaObject::connectSlotsByName(Form);
    } // setupUi

    void retranslateUi(QWidget *Form)
    {
        Form->setWindowTitle(QApplication::translate("Form", "Form", 0, QApplication::UnicodeUTF8));
        AnnotationFilter->setTitle(QApplication::translate("Form", "Filtering", 0, QApplication::UnicodeUTF8));
        GrpFeature->setTitle(QApplication::translate("Form", "Feature Level Filtering", 0, QApplication::UnicodeUTF8));
        btn_RL1->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        btn_LR1->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("Form", "Selected Feature Categories", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("Form", "Feature Categories", 0, QApplication::UnicodeUTF8));
        date->setTitle(QApplication::translate("Form", "date", 0, QApplication::UnicodeUTF8));
        dateEdit_2->setDisplayFormat(QApplication::translate("Form", "yyyy/MM/dd", 0, QApplication::UnicodeUTF8));
        dateEdit->setDisplayFormat(QApplication::translate("Form", "yyyy/MM/dd", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("Form", "START", 0, QApplication::UnicodeUTF8));
        chk_date->setText(QApplication::translate("Form", "All Date?", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("Form", "END", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("Form", "Event Category", 0, QApplication::UnicodeUTF8));
        chk_fcm_event->setText(QApplication::translate("Form", "FCM", 0, QApplication::UnicodeUTF8));
        chk_radar->setText(QApplication::translate("Form", "Radar", 0, QApplication::UnicodeUTF8));
        chk_user_event->setText(QApplication::translate("Form", "Manual", 0, QApplication::UnicodeUTF8));
        chk_eyeq_event->setText(QApplication::translate("Form", "EyeQ", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("Form", "Day Type", 0, QApplication::UnicodeUTF8));
        chk_day_1->setText(QApplication::translate("Form", "Day", 0, QApplication::UnicodeUTF8));
        chk_day_3->setText(QApplication::translate("Form", "Night", 0, QApplication::UnicodeUTF8));
        chk_day_2->setText(QApplication::translate("Form", "Dusk", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("Form", "Weather Type", 0, QApplication::UnicodeUTF8));
        chk_weather_1->setText(QApplication::translate("Form", "Clear", 0, QApplication::UnicodeUTF8));
        chk_weather_4->setText(QApplication::translate("Form", "Snow", 0, QApplication::UnicodeUTF8));
        chk_weather_3->setText(QApplication::translate("Form", "Overcast", 0, QApplication::UnicodeUTF8));
        chk_weather_2->setText(QApplication::translate("Form", "Rain", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("Form", "Road Type", 0, QApplication::UnicodeUTF8));
        chk_road_1->setText(QApplication::translate("Form", "Highway", 0, QApplication::UnicodeUTF8));
        chk_road_3->setText(QApplication::translate("Form", "Both", 0, QApplication::UnicodeUTF8));
        chk_road_2->setText(QApplication::translate("Form", "Urban", 0, QApplication::UnicodeUTF8));
        groupBox_5->setTitle(QApplication::translate("Form", "Event Status", 0, QApplication::UnicodeUTF8));
        chk_event_status_1->setText(QApplication::translate("Form", "Unconfirmed", 0, QApplication::UnicodeUTF8));
        chk_event_status_3->setText(QApplication::translate("Form", "Annotated", 0, QApplication::UnicodeUTF8));
        chk_event_status_2->setText(QApplication::translate("Form", "Accepted", 0, QApplication::UnicodeUTF8));
        chk_event_status_4->setText(QApplication::translate("Form", "Declined", 0, QApplication::UnicodeUTF8));
        chk_event_status_5->setText(QApplication::translate("Form", "Missed", 0, QApplication::UnicodeUTF8));
        GrpEvent->setTitle(QApplication::translate("Form", "Event Level Filtering", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("Form", "Events", 0, QApplication::UnicodeUTF8));
        btn_RL3->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("Form", "Selected Predefined Annotation", 0, QApplication::UnicodeUTF8));
        btn_LR3->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        btn_LR2->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("Form", "Selected Events", 0, QApplication::UnicodeUTF8));
        btn_RL2->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        chk_annotation->setText(QApplication::translate("Form", "By Predefined Annotation?", 0, QApplication::UnicodeUTF8));
        chk_search->setText(QApplication::translate("Form", "By Search?", 0, QApplication::UnicodeUTF8));
        listSelectedAI->setText(QApplication::translate("Form", "Selected Add. Info.", 0, QApplication::UnicodeUTF8));
        btn_RL4->setText(QApplication::translate("Form", "REMOVE", 0, QApplication::UnicodeUTF8));
        btn_LR4->setText(QApplication::translate("Form", "ADD", 0, QApplication::UnicodeUTF8));
        chk_AI->setText(QApplication::translate("Form", "All AI?", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("Form", "Project", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("Form", "Selected Project", 0, QApplication::UnicodeUTF8));
        chk_tour->setText(QApplication::translate("Form", "All Collection?", 0, QApplication::UnicodeUTF8));
        btn_LR->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        btn_RL->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        btn_RL0->setText(QApplication::translate("Form", "<<", 0, QApplication::UnicodeUTF8));
        btn_LR0->setText(QApplication::translate("Form", ">>", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("Form", "Selected VIN", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("Form", "VIN", 0, QApplication::UnicodeUTF8));
        GrpEdit->setTitle(QApplication::translate("Form", "Event Review", 0, QApplication::UnicodeUTF8));
        grp_annotation->setTitle(QApplication::translate("Form", "Review", 0, QApplication::UnicodeUTF8));
        btn_insert->setText(QApplication::translate("Form", "Insert", 0, QApplication::UnicodeUTF8));
        btn_copy->setText(QApplication::translate("Form", "Copy Clip", 0, QApplication::UnicodeUTF8));
        chk_text_annotation->setText(QApplication::translate("Form", "Use Predifined Annotation?", 0, QApplication::UnicodeUTF8));
        lbl_clip->setText(QString());
        btn_next->setText(QApplication::translate("Form", "NEXT >>", 0, QApplication::UnicodeUTF8));
        btn_update->setText(QApplication::translate("Form", "Update", 0, QApplication::UnicodeUTF8));
        lbl_table->setText(QApplication::translate("Form", "TextLabel", 0, QApplication::UnicodeUTF8));
        lbl_status->setText(QString());
        lbl_reportid->setText(QApplication::translate("Form", "TextLabel", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("Form", "Event Status", 0, QApplication::UnicodeUTF8));
        btn_prev->setText(QApplication::translate("Form", "<< PREVIOUS", 0, QApplication::UnicodeUTF8));
        lbl_adtftime->setText(QString());
        btn_showclip->setText(QApplication::translate("Form", "Show Clip", 0, QApplication::UnicodeUTF8));
        grp_playlist->setTitle(QApplication::translate("Form", "PlayList", 0, QApplication::UnicodeUTF8));
        btn_generate->setText(QApplication::translate("Form", "Generate Play-List", 0, QApplication::UnicodeUTF8));
        lbl_status_playlist->setText(QString());
        btn_show_playlist->setText(QApplication::translate("Form", "<", 0, QApplication::UnicodeUTF8));
        GrpInsert->setTitle(QApplication::translate("Form", "Event Data Insertion", 0, QApplication::UnicodeUTF8));
        btn_submit->setText(QApplication::translate("Form", "Insert", 0, QApplication::UnicodeUTF8));
        btn_cancel->setText(QApplication::translate("Form", "Cancel", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("Form", "Clip Name*", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("Form", "Event Time", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("Form", "Event Status*", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("Form", "m", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("Form", "s", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("Form", "ms", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("Form", "Feature*", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("Form", "Event*", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("Form", "VIN*", 0, QApplication::UnicodeUTF8));
        chk_i_text_annotation->setText(QApplication::translate("Form", "Annotation*", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("Form", "EVENT INSERT \n"
" MODE", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("Form", "Project*", 0, QApplication::UnicodeUTF8));
        btn_setting->setText(QApplication::translate("Form", "SQL Upload", 0, QApplication::UnicodeUTF8));
        btn_clip->setText(QApplication::translate("Form", "Clip Directory Browse", 0, QApplication::UnicodeUTF8));
        grp_login->setTitle(QApplication::translate("Form", "LOG-IN", 0, QApplication::UnicodeUTF8));
        btn_login->setText(QApplication::translate("Form", "Log-In", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("Form", "ID", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("Form", "Password", 0, QApplication::UnicodeUTF8));
        btn_change_pw->setText(QApplication::translate("Form", "PW Change", 0, QApplication::UnicodeUTF8));
        grp_pwchange->setTitle(QApplication::translate("Form", "PW Change", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("Form", "ID", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("Form", "Current PW", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("Form", "New PW", 0, QApplication::UnicodeUTF8));
        btn_change->setText(QApplication::translate("Form", "Change", 0, QApplication::UnicodeUTF8));
        btn_change_cancel->setText(QApplication::translate("Form", "Cancel", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("Form", "New PW", 0, QApplication::UnicodeUTF8));
        lbl_user->setText(QString());
        GrpSetting->setTitle(QApplication::translate("Form", "Event Data Insertion", 0, QApplication::UnicodeUTF8));
        btn_execute->setText(QApplication::translate("Form", "Execute", 0, QApplication::UnicodeUTF8));
        btn_browse->setText(QApplication::translate("Form", "SQL File Browse", 0, QApplication::UnicodeUTF8));
        btn_setting_cancel->setText(QApplication::translate("Form", "Cancel", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("Form", "Setting  MODE", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Form: public Ui_Form {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GUIFRONTEND_H
